### ISSUE TITLE
Add powershell activation scripts?

### ISSUE THREAD

**Issue by WardBrian** [conda-forge/clang-win-activation-feedstock#41]
### Comment:

Hello!

I'm hoping to use this in https://github.com/conda-forge/cmdstan-feedstock, which is a bit odd in that it actually requires compilers at _run_ time. As such, it would be great if the activation also supported Powershell environments with `[de]activate_*.ps1` scripts

I'm happy to open a PR which adds these, but I wanted to confirm first that it would be likely to be accepted. 

Thanks!

**Comment by h-vetinari** [comment]
Sure, go for it!
