### ISSUE TITLE
Alternative source for MSVC headers

### ISSUE THREAD

**Issue by xhochy** [conda-forge/clang-win-activation-feedstock#7]
`https://www.nuget.org/api/v2/package/VisualCppTools.Community.VS2017Layout/${MSVC_HEADERS_VERSION}` is sadly discontinued and only has the 14.11 headers but we would need the 14.16 headers to be in line with what we are using the vc-feedstock.

One alternative could be to use `wine` to run `vs_buildtools.exe --quiet --wait --norestart --nocache  --installPath --add Microsoft.VisualStudio.Component.VC.v141 --add C:\BuildTools Microsoft.VisualStudio.Component.VC.v141.x86.x64` (not tried yet).

**Comment by isuruf** [comment]
Fixed now
